site_name: Component-Based Architecture Project
site_description: "A professional-grade template for modern Python projects with AI and Mail services."

theme:
  name: material
  palette:
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tabs
    - content.code.copy

nav:
  - 'Overview': 'index.md'
  - 'Architecture': 'component.md'
  - 'AI Service Stack':
    - 'Overview': 'ai/overview.md'
    - 'AI API': 'ai/ai_api.md'
    - 'OpenAI Implementation': 'ai/openai_impl.md'
    - 'AI Service': 'ai/ai_service.md'
    - 'AI Adapter': 'ai/ai_adapter.md'
    - 'AI Service Client': 'ai/ai_service_client.md'
  - 'Mail Client Stack':
    - 'Overview': 'mail/overview.md'
    - 'Mail Client API': 'api/mail_client_api.md'
    - 'Gmail Client Implementation': 'api/gmail_client_impl.md'
  - 'Testing': 'testing.md'
  - 'CI/CD': 'circleci-setup.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src/ai_api/src
            - src/openai_impl/src
            - src/ai_service/src
            - src/ai_adapter/src
            - src/ai_service_client
            - src/mail_client_api/src
            - src/gmail_client_impl/src
            - src/mail_client_service/src
            - src/mail_client_adapter/src
            - src/mail_client_service_client
          options:
            show_source: false
            docstring_section_style: spacy
            members_order: source
