global:
  scrape_interval: 15s # Increased interval for external scraping

scrape_configs:
  - job_name: "ai_ticket_service_render"
    metrics_path: "/metrics"
    scheme: "https"
    static_configs:
      - targets: ["oss-nml.onrender.com"]